# config.yml

backend:
  name: git-gateway
  branch: master

site_url: https://allanswitzer.com

display_url: https://allanswitzer.com

logo_url: https://allanswitzer.com/uploads/margaret-ching454.png

search: false

media_folder: '/uploads'

collections:
  - name: "posts" # Used in routes, e.g., /admin/collections/blog

    label: "Posts"

    folder: "_posts"

    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"

    create: true # Allow users to create new documents in this collection

    fields:
      - label: "Year"
        name: "year"
        widget: "string"
        default: "--"

      - label: "Category"
        name: "category"
        widget: "select"
        options: ["Works on Paper", "Photo Works", "Paintings", "Sculpture", "Reviews", "Exhibitions", "Misc."]

      - label: "Title"
        name: "title"
        widget: "string"

      - label: "Description"
        name: "description"
        widget: "string"

      - label: "Images"
        name: "images"
        widget: "image"
        allow_multiple: true
        choose_url: false
        media_library:
          config:
            multiple: true
