# config.yml

backend:
  name: git-gateway
  branch: master
media_folder: '/uploads'
collections:
  - name: "posts" # Used in routes, e.g., /admin/collections/blog
    label: "Posts" # Used in the UI
    folder: "_posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection

    fields: # The fields for each document, usually in front matter
      - {label: "Year", name: "year", widget: "string", default: "--"}
      - {label: "Category", name: "category", widget: "select", options: ["Works on Paper", "Photo Works", "Paintings", "Sculpture", "Reviews", "Exhibitions", "Misc."]}
      - {label: "Images", name: "images", widget: "image", multiple: "true", media_library: {allow_multiple: "true"}}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}

      